python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/foundation/prad/mskcc/foundation
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/foundation/mixed/lymphoma-sa/therp/mskcc/foundation
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/foundation/mixed/lymphoma-sa/therp/filtered/mskcc/foundation
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/foundation/mixed/lymphoma/filtered/mskcc/foundation
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/foundation/mixed/lymphoma/merged/mskcc/foundation
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/foundation/mixed/lymphoma/merged/filtered/mskcc/foundation
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/foundation/mixed/lymphoma/mskcc/foundation
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/foundation/gbm/mellinghoff
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/foundation/mixed/lymphoma/younes
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/foundation/mixed/lymph/mskcc/foundation/160830
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/foundation/lymph/landscape/fmi
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/foundation/dlbc/13-082/mskcc/foundation
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/foundation/coadread/mskcc/foundation