python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/laml/target
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/stad/tcga/pub
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/stad/duke_nus/2012
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/stad/fmi/2014
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/stad/mskcc
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/stad/mskcc/yoon
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/lusc/tcga
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/lusc/tcga/pub
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/rcc/utsw/2012
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/cclp/sanger
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/nsclc_tracerx_2017
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/dlbcl_uorouen_2016
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/plmeso/tcga/pub
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/plmeso/genentech/2016
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/uvm/tcga/pub
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/lihc/tcga/pub
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/ovt/levine/2015
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/set_weiser1_10860
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/luad
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/luad/su2c
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/luad/mskcc/viale
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/luad/merged3
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/luad/merged
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/hcc_msk_venturaa_2018
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/test_ritika/brafresit
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/set_weiser1_10860B
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/cellline/cclp/sanger
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/cellline/douglevine_ccl
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/cellline/mskcc
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/ucec/mskcc/levine
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/ucec/mskcc/levine_2015
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/mixed/poetic_consolidated
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/mixed/oberg_pipseq_2017
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/mixed/akt_2015
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/mixed/mskimpact_pp
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/mixed/genie
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/mixed/poetic
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/mixed/accrf
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/mixed/accrf/mskimpact
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/mixed/accrf/fmi/unpub
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/mixed/accrf/merged/unfiltered
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/mixed/accrf/merged/filtered
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/mixed/poetic_impact
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/brca/washu/esr1_pdx/2013
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/brca/gray
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/brca/brca_mbcproject2_wagle_2017
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/brca/scand
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/lgg/tcga/pub
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/set_weiser1_10860C
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/set_weiser1_10860D
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/ov/jhu/velculesculab/2015
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/fl/unmc
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/dlbc/2015
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/dlbc/2016
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/crc_msk_2017
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/all/target/phase2
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/all/target/phase1
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/ccle_broad_2019
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/ccrcc/sanger/2012
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/esca/tcga/pub
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/prad/su2c
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/prad/cornell
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/prad/cornell/2016
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/prad/su2c_impact
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/prad/tcga_su2c_impact/2015
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/prad/su2c_test
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/lcll/icgc/2011
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/hnsc/mskcc/berger/2013
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/hnsc/mskcc/berger/dogan
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/hnsc/mskcc/berger/dogan/2013
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/um_qimr_2016
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/um/qimr_berghofer/2015
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/acyc/sanger/unpub
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/acyc/jhu/unpub
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/acyc/jhu/2011
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/acyc/fmi/morris/unfiltered
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/acyc/fmi/morris/2017
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/acyc/accrf_lmorris_analysis_primary
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/acyc/accrf_lmorris_analysis_merged
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/acyc/accrf_lmorris_analysis_recur_met
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/acyc/mskcc/unpub
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/blca_msk_tcga_2020
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/brca_pdx_bcm_2013
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/sclc/sclc_cwru_n62
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/sclc/sclc_cwru_n90
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/aml/shanghai/2011
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/aml/wustl/2012
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/paad/mskcc/basturk/2013
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/skcm/tcga_pub_2015
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/skcm/pici/msk/2016
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/skcm/mskcc/2015/chant
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/skcm/mskcc/2015/chant2
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/skcm/mskcc/solit/2013
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/skcm/mskcc/solit/2012
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/blca_eugene_2020
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/egc/mskcc/2015/janjigiany
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/gbm/ivy/dfci/2015
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/gbm/ivy/msk_2015
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/gbm/ivy/dfci_impact/2015
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/gbm/mskcc/mellingi/ge
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/bcc_unige_2016
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/pcnsl/mskcc/mellingi
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/pcnsl/mskcc/5667_filtered
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/plmeso_tcga_pub_2018
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/thca/mskcc/faginj/2014
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/coadread/mskcc_cmo_4495_gamma
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/coadread/seoul/2013
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/coadread/caseccc_2014
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/coadread/mskcc_cmo_4495_beta
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/sarc/tester
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/os/target
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/nbl/target
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/cesc/tcga/pub
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/chol/tcga/pub
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/ihch_ehsh_2014
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/es/nih/2014
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/metastatic_solid_tumors_mich_2017
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/mrt/broad/2012
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/thhc/mskcc/2015/chant
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/ucs/tcga/pub
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/chdm_bolan_gounder_2017
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/vsc_cuk_2018
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/mixed_wustl_2016
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/summit_2017
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/blca_wcm_2016
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/utuc_wcm_2016
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/cll/2016
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/cll/broad/2015
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/scbc/ucsf
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/blca/mskcc/cmo-impact/2015
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/blca/mskcc/solit/2013
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/blca/mskcc/solit/2015
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/msk_solid_heme_subset
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/wt/target
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/coad_caseccc_2015
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/nsclc/nsclc_science_2015
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/gct/tcga/freeze
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/gct/mskcc/impact_cmo
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/ilc/bordet/2016
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/mov/mskcc/2015
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/cbio-portal-data/studies/acc/tcga/2016