python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/stad/mskcc/tang_2014
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/lusc/mskcc/paik_2014
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/lcnec/mskcc/rekhtman/2014
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/mixed/dmp/TSACP/2013
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/mixed/dmp/MSK-IMPACT/2013
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/brca/mskcc/wen
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/brca/mskcc/chandarlapaty/2014
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/lcarc/mskcc/rekhtman_2014
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/mixed_cmo_access_2021
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/rudinc_cmo/06437_h_468_p1_zp
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/rudinc_cmo/06437_h_410_p1_zp
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/sclc/mskcc/rekhtman_2014
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/sclc/mskcc/pietanza_2014
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/lune/mskcc/rekhtman_impact_2015
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/lune/mskcc/rekhtman_2014
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/urcc/mskcc
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/9_public
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/9_public/case_lists
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/blca/mskcc/sc
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/blca/mskcc/signet_ring
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/blca/mskcc/bkm
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/blca/mskcc/prog
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/chrcc/mskcc/2015
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/coadread_vakianie_impact_cmo_2018
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/stad/mskcc/2016
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/egc_mskcc_2016
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/idc/cmo/bergerm1/6039_b_merged
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/blca_solit_mskcc_2017
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/YC_prorg_impact
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/chdm_impact_foundation_2017
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/mpn/mskcc/2015
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/lung/panlung/2016
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/coadread_mskcc_cmo_foundation
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/rcc_impact_08052
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/mixed/cmo/hymand/5257_p_impact
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/mixed/mskcc/hymand/2016
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/thpa_cmo_hoa_06717_g_impact
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/crc_jga_msk_2019_test
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/hcc_amc_tcga_2016
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/crc_hepatic_msk_2018
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/bladder_impact_msk_2018
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/hcc_07668_impact
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/gct_ds_test_04430_impact_2016
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/biliary_tract_cmo_basturko_07578_c_06440_b
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/ipmn_06440b_2017
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/jc_cmo_impact_2019
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/prad_p1000_v2
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/gbm/fmi_mskcc/2016
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/ihch/mskcc/2016
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/brca_cmo_06938_impact
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/mixed_puma_cmo_impact_2017
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/lung_5830_impact_2017
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/crc_jga_msk_2019
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/coadread/coadread_garciaaj_cmo_impact_2016
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/coadread/cmo/offitk_06246_b_impact
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/coadread/saltzl/2015
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/rcc_mskcc_hsiehj_2016
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/lung_pdx_internal_2021
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/mixed_ds_puma_impact_2017
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/lune_mskcc_ladanyim_2016
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/thyroid/mskcc/ganly
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/thyroid/mskcc/faginj_4773_impact
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/apad_mskcc_berger_2016
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/blca_plasmacytoid/mskcc/2016
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/blca_plasmacytoid/mskcc/signet_ring_impact
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/blca_plasmacytoid/mskcc/rosenbj1_JR_ddgc_impact
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/egc_impact_freeze_2016
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/gbc_impact_06836b_2016
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/ihch_mskcc_2017
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/bladder_msk_2017
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/omuro_6170_b_ao_cmo_impact_2017
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/egc_impact_cfdna_2017
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/gct_mskcc_2020
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/blca/mskcc/ddgc_2016
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/blca/mskcc/rosenbj1_JR_ddgc_impact
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/egc_msk_janjigy_2017
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/sclc_oliver_cmo_merge
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/ihch_impact_cmo_2018
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/blca_td_metbla_impact_2018
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/impact/MERGED/blca_msk_tcga_dfci_2016