python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/blca_bcan_hcrn_2015
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/perineural_invasion_impact_2018
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/chol_msk_2018
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/esca_mskcc_2020
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/skcm_dfci_2015
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/plmeso_impact_cmo_2018
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/wt_stjude_2017
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/cllsll_msk_mgh_2020
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/egc_mskcc_2020
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/brca_pdx_bcm_2016
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/gbc_msk_2018
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/prad_pik3r1_msk_2021
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/skcm_mskcc_2014
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/mskimpact_foundation_2019
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/test_2018
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/blca_msk_2021
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/mixed_ds_micpap_impact
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/pdac_mskimpact_2019
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/blca_msk_2019
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/mixed_impact_ucla_2021
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/esca_cmo10576_impact_merge_2020
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/radiogenomicsb2_glioma_2019
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/blca_tcga_2019
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/mskimpact_heme
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/mm_mmrf_2018
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/brca_tcga_2015_test
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/blca_solitd_cmo_2020_lab_access
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/utuc_merged_cohort2_2019
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/mixed_solitd_ds_ubad_2019
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/mng_utoronto_2021
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/bone_ddpcr_shuklan_2018
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/bone_msk_2017
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/glioma_dfci_2020
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/prad_fm_2016
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/mixed_pdx_aacf_manual
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/mixed_msk_mdanderson_2020
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/sclc_dowlatilab_n12_2018
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/prad_impact_2019
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/brca_msk_li_2019
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/ucec_osu_2019
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/bladder_merge_msk_2017
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/mixed_pdx_msk_manual
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/genie_submission_test
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/acc_tcga_pan_can_atlas_2018
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/blca_mskimpact_copath
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/grail_2016/validation_prostate
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/grail_2016/early_stage_breast
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/grail_2016/neo_breast
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/grail_2016/validation_lung
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/grail_2016/met_breast
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/grail_2016/agc
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/grail_2016/preop_lung
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/grail_2016/met_lung
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/grail_2016/brca_autopsy
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/grail_2016/validation_breast
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/blca_cyto_bcg_mskcc_2017
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/angs_painter_2020
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/angs_painter_2020/test_cdd_2020
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/sclc_cmo_2017
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/mixed_mskcc_cud_wes_2016
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/mixed_CR_pdx_impact_2018
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/mixed_DS_puma_2020
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/blca_tcga_msk_2019
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/mixed_cohort_2020
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/luad_msk_npjpo_2021
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/ntrk_msk_2019
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/crlm_msk_2020
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/blad_msk_ahmadie_2021
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/blsc_msk_2020
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/brca_pdx_2016
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/blca_solitd_cmo_2020_external_access
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/coadread_mskimpact_2018
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/esmo_msk_2021
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/mixed_DS_puma_2019
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/read_cbe_garciaaj_JGA_rectal_impact
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/ansc_msk_2018
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/nbl_ped_msk_2019
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/chol_mskimpact_cmo_merge
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/mixed_ped_pdx_2017
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/hgsoc_ubc_2018
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/stomach_impact_2019
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/msk_archer_2020
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/egc_trap_msk_2020
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/paad_cid
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/mixed_msk_viral_2019
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/brca_mapk_hp_msk_2021
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/glioma_radiogenomic_2018
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/brca_impact_06938_bc_zp_2016
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/mel_mskimpact_2018
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/ihch_chol_msk_2019
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/stomach_impact_2018
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/dlbcl_impact_fmi_2018_test
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/pdx_kids_2019
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/coadread_msk_2020
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/panet_msk_2017
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/luad_mskcc_2020_met_organotropism
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/pancan_pcawg_2020
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/pancan_pcawg_2020/DCC_data
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/mskimpact_13162_2021
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/egc_trap_msk_2019
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/esophageal_impact_2019
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/prad_mskimpact_2020
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/prad_mpcproject_2018
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/ihch_smmu_2014
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/crc_mskcc_bpc_2020
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/sclc_minnalab_2017
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/liver_mskimpact_2017
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/luad_cellline_utsw_2016
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/crc_met_organoids_2021
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/thyroid_NLe_imrt_impact_2018
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/brca_akt1_genie_2019
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/htan_test_2021
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/lung_ctdx_msk_2021
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/mixed_selpercatinib_2020
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/es_nancy_test
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/msk_met_2021
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/mbc_genie_2020
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/mixed_test
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/rcc_msk_2021
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/egc_siewert_msk_2021
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/oscf_hameed_2018
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/blood_msk_2017
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/mixed_impact_wes_2017
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/mixed_access_2020
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/mixed_msk
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/breast_faan_2019
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/pilot_msk_melpcm2_test
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/radiographic_glioma_2017
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/blca_cmo_06155_2016
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/set_solitd_2021
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/cornell_test_data
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/blca_cmo_impact_2016
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/chordoma_mskcc_2021
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/aml_ohsu_2018
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/nsclc_mskcc_bpc_2020
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/sclc_washu_2018
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/prad_mskcc_2020
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/dlbcl_impact_fmi_2018
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/pi_af_0c_08436_D_manual
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/oncohistone_rockefeller_2018
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/puma_neratinib_2017
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/crc_mskimpact_2017
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/hccihch_pku_2019
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/luad_joneslab_2019
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/nsclc_msk_subset_2018
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/sclc_mgh_2018
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/egc_impact_2019
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/mel_dfci_2019
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/mixed_pdx_ntrk_manual
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/brain_pdx_msk_2021
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/prad_su2c_2019
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/mixed_gray_proj_06208
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/bladder_msk_2021
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/sarcoma_msk_2020
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/lymphoma_super_cohort_fmi_msk_060518
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/rbl_mskcc_2020
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/um_msk_2019
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/crc_eo_2020
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/prad_su2c_2018
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/set_mellingi_impact
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/msk_impact_ch_2020
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/lgg_msk_2020
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/brain_pdx_msk_2018
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/genie_mskimpact_2016
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/mixed_msk_2021
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/nsclc/nsclc_tracerx_2017
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/crc_genie_bpc
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/coadread_crc1000_2016
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/ampca_msk_2019
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/mixed_pipseq_2019
python3 gene_cleanup_data_file_migration.py -path /Users/suny1/mercurial/private/coadread_mss_msk_2018