bash file_rename.sh acc_2019
bash file_rename.sh acyc_fmi_2014
bash file_rename.sh all_stjude_2015
bash file_rename.sh bcc_unige_2016
bash file_rename.sh blca_msk_tcga_2020
bash file_rename.sh blca_mskcc_solit_2012
bash file_rename.sh blca_mskcc_solit_2014
bash file_rename.sh blca_nmibc_2017
bash file_rename.sh blca_plasmacytoid_mskcc_2016
bash file_rename.sh brca_metabric
bash file_rename.sh breast_alpelisib_2020
bash file_rename.sh breast_msk_2018
bash file_rename.sh cellline_ccle_broad
bash file_rename.sh cfdna_msk_2019
bash file_rename.sh chol_msk_2018
bash file_rename.sh coadread_mskcc
bash file_rename.sh crc_msk_2017
bash file_rename.sh cscc_dfarber_2015
bash file_rename.sh egc_msk_2017
bash file_rename.sh egc_mskcc_2020
bash file_rename.sh egc_trap_msk_2020
bash file_rename.sh escc_ucla_2014
bash file_rename.sh gbc_msk_2018
bash file_rename.sh gbm_tcga_pub
bash file_rename.sh gct_msk_2020
bash file_rename.sh glioma_msk_2018
bash file_rename.sh glioma_mskcc_2019
bash file_rename.sh hcc_msk_venturaa_2018
bash file_rename.sh hcc_mskimpact_2018
bash file_rename.sh histiocytosis_cobi_msk_2019
bash file_rename.sh hnc_mskcc_2016
bash file_rename.sh ihch_msk_2021
bash file_rename.sh ihch_mskcc_2020
bash file_rename.sh luad_mskcc_2020
bash file_rename.sh luad_tsp
bash file_rename.sh lung_msk_2017
bash file_rename.sh lung_msk_pdx
bash file_rename.sh lymphoma_cellline_msk_2020
bash file_rename.sh mbc_msk_2021
bash file_rename.sh mds_mskcc_2020
bash file_rename.sh mel_mskimpact_2020
bash file_rename.sh mixed_cfdna_msk_2020
bash file_rename.sh mnm_washu_2016
bash file_rename.sh mpnst_mskcc
bash file_rename.sh msk_access_2021
bash file_rename.sh msk_impact_2017
bash file_rename.sh nsclc_pd1_msk_2018
bash file_rename.sh nsclc_unito_2016
bash file_rename.sh odg_msk_2017
bash file_rename.sh prad_cdk12_mskcc_2020
bash file_rename.sh prad_mcspc_mskcc_2020
bash file_rename.sh prad_msk_2019
bash file_rename.sh prad_mskcc
bash file_rename.sh prad_mskcc_2017
bash file_rename.sh rbl_cfdna_msk_2020
bash file_rename.sh rbl_mskcc_2020
bash file_rename.sh rectal_msk_2019
bash file_rename.sh sarc_mskcc
bash file_rename.sh scco_mskcc
bash file_rename.sh skcm_vanderbilt_mskcc_2015
bash file_rename.sh summit_2018
bash file_rename.sh thyroid_mskcc_2016
bash file_rename.sh tmb_mskcc_2018
bash file_rename.sh ucec_msk_2018
bash file_rename.sh urcc_mskcc_2016
bash file_rename.sh usarc_msk_2020
bash file_rename.sh utuc_msk_2019
bash file_rename.sh utuc_mskcc_2015
bash file_rename.sh utuc_pdx_msk_2019