bash run_tmb_script.sh acc_2019
bash run_tmb_script.sh acyc_fmi_2014
bash run_tmb_script.sh all_stjude_2015
bash run_tmb_script.sh bcc_unige_2016
bash run_tmb_script.sh blca_msk_tcga_2020
bash run_tmb_script.sh blca_mskcc_solit_2012
bash run_tmb_script.sh blca_mskcc_solit_2014
bash run_tmb_script.sh blca_nmibc_2017
bash run_tmb_script.sh blca_plasmacytoid_mskcc_2016
bash run_tmb_script.sh brca_metabric
bash run_tmb_script.sh breast_alpelisib_2020
bash run_tmb_script.sh breast_msk_2018
bash run_tmb_script.sh cellline_ccle_broad
bash run_tmb_script.sh cfdna_msk_2019
bash run_tmb_script.sh chol_msk_2018
bash run_tmb_script.sh coadread_mskcc
bash run_tmb_script.sh crc_msk_2017
bash run_tmb_script.sh cscc_dfarber_2015
bash run_tmb_script.sh egc_msk_2017
bash run_tmb_script.sh egc_mskcc_2020
bash run_tmb_script.sh egc_trap_msk_2020
bash run_tmb_script.sh escc_ucla_2014
bash run_tmb_script.sh gbc_msk_2018
bash run_tmb_script.sh gbm_tcga_pub
bash run_tmb_script.sh gct_msk_2020
bash run_tmb_script.sh glioma_msk_2018
bash run_tmb_script.sh glioma_mskcc_2019
bash run_tmb_script.sh hcc_msk_venturaa_2018
bash run_tmb_script.sh hcc_mskimpact_2018
bash run_tmb_script.sh histiocytosis_cobi_msk_2019
bash run_tmb_script.sh hnc_mskcc_2016
bash run_tmb_script.sh ihch_msk_2021
bash run_tmb_script.sh ihch_mskcc_2020
bash run_tmb_script.sh luad_mskcc_2020
bash run_tmb_script.sh luad_tsp
bash run_tmb_script.sh lung_msk_2017
bash run_tmb_script.sh lung_msk_pdx
bash run_tmb_script.sh lymphoma_cellline_msk_2020
bash run_tmb_script.sh mbc_msk_2021
bash run_tmb_script.sh mds_mskcc_2020
bash run_tmb_script.sh mel_mskimpact_2020
bash run_tmb_script.sh mixed_cfdna_msk_2020
bash run_tmb_script.sh mnm_washu_2016
bash run_tmb_script.sh mpnst_mskcc
bash run_tmb_script.sh msk_access_2021
bash run_tmb_script.sh msk_impact_2017
bash run_tmb_script.sh nsclc_pd1_msk_2018
bash run_tmb_script.sh nsclc_unito_2016
bash run_tmb_script.sh odg_msk_2017
bash run_tmb_script.sh prad_cdk12_mskcc_2020
bash run_tmb_script.sh prad_mcspc_mskcc_2020
bash run_tmb_script.sh prad_msk_2019
bash run_tmb_script.sh prad_mskcc
bash run_tmb_script.sh prad_mskcc_2017
bash run_tmb_script.sh rbl_cfdna_msk_2020
bash run_tmb_script.sh rbl_mskcc_2020
bash run_tmb_script.sh rectal_msk_2019
bash run_tmb_script.sh sarc_mskcc
bash run_tmb_script.sh scco_mskcc
bash run_tmb_script.sh skcm_vanderbilt_mskcc_2015
bash run_tmb_script.sh summit_2018
bash run_tmb_script.sh thyroid_mskcc_2016
bash run_tmb_script.sh tmb_mskcc_2018
bash run_tmb_script.sh ucec_msk_2018
bash run_tmb_script.sh urcc_mskcc_2016
bash run_tmb_script.sh usarc_msk_2020
bash run_tmb_script.sh utuc_msk_2019
bash run_tmb_script.sh utuc_mskcc_2015
bash run_tmb_script.sh utuc_pdx_msk_2019